### ISSUE TITLE
Vorige / volgende week in auto-overzichten

### ISSUE THREAD

**Issue by kcoolsae** [degage/degapp#101]

**Comment by genoot** [comment]
Ook deze wordt gemist. 
Ontlener kan nu al in het dagoverzicht naar volgende/vorige dag gaan.
Eigenaar zou ook graag in weekoverzicht naar volgende/vorige week gaan.

**Comment by genoot** [comment]
bij user_id 565, en bij uitbreiding alle eigenaars met 2 auto's, werken de pijltjes niet naar behoren.
enkel bij de eerste auto werkt het scrollen correct
