### ISSUE TITLE
info over infosessies buiten app tonen

### ISSUE THREAD

**Issue by genoot** [degage/degapp#110]
De komende infosessies willen we graag op de website buiten de app tonen.

datum / type / aantal deelnemers vs aantal plaatsen / straat

alle komende sessies mogen getoond, ook diegene die volzet zijn.

Naam gastgezin of juiste adres mag niet publiek.
Enkel straatnaam zodat men op basis vd buurt kan kiezen.

**Comment by kcoolsae** [comment]
Pagina kan opgehaald worden via URL /degapp/infosessions

Kan best opgenomen worden in een iframe in een grotere pagina

Er moet een CSS-bestand gemaakt worden met URL /website/degapp.css (= standaardplaats voor wordpress) daarin kan de tabel naar believen worden 'gestyled'.

**Comment by genoot** [comment]
is het haalbaar om de info op te splitsen naargelang type infosessie : ontlener/eigenaar/andere ?
we zouden die apart op de website willen weergeven (3 iframes) omdat de nieuwe website andere pagina's heeft voor ontlener en eigenaar.
er mag ook een koppelteken tss straat en gemeente, of gemeente tss haakjes

**Comment by genoot** [comment]
ziet er nu zo uit:

![infosessies-website](https://cloud.githubusercontent.com/assets/9049321/21718798/188575ca-d41a-11e6-941a-c6e51ad207a5.png)
