### ISSUE TITLE
Automatische goedkeuring van reservaties misschien geen goed idee?

### ISSUE THREAD

**Issue by kcoolsae** [degage/degapp#123]
Nu worden reservaties automatische goedgekeurd wanneer de eigenaar niet gereageerd heeft binnen de  4320 minuten (= 72 uur). Niet iedereen is daar zo gelukkig mee...

Gelieve te beslissen wat hiermee moet gebeuren. Opties
- Tijdsduur verlengen
- Na een bepaalde tijd de gebruiker verwittigen dat eigenaar nog niet gereageerd heeft met bericht
- ... idem ... met e-mail

**Comment by genoot** [comment]
dit bleek idd geen goed idee
