### ISSUE TITLE
Aanvinken dat het contract is getekend

### ISSUE THREAD

**Issue by kcoolsae** [degage/degapp#172]
Een contractverantwoordelijke moet kunnen aanvinken dat het contract is getekend. Een admin moet deze informatie hebben om een gebruiker _full user_ te kunnen maken.

**Comment by genoot** [comment]
Best ook contractdatum kunnen invullen; vaak is er nogal een tijdsverschil tss tekenen/betalen/lid worden. De contractdatum komt of de factuur voor het inschrijvingsgeld

**Comment by genoot** [comment]
naam contractverantwoordelijke verandert in naam van diegene die de flow afrondt.
dat gebeurt beter niet want contractverantwoordelijke is diegene die het contract mee ondertekent, dat onthouden we best.

**Comment by driesdv** [comment]
Ik heb dat proberen reproduceren maar de naam van de contractverantwoordelijke veranderde niet. Kan je daar meer details voor aanleveren?
