### ISSUE TITLE
status geblokkeerd lid

### ISSUE THREAD

**Issue by genoot** [degage/degapp#212]
een lid kan nu geblokkeerd worden, maar zonder onderscheid
in de praktijk heb je 

1/ iemand die uitstapt -> voor de ledenlijst is dit een -ex-lid; telt niet meer in aantal leden; de uitstapdatum is belangrijk
deze persoon mag niet meer inloggen.
wellicht moet voor de privacy voorzien worden dat we de gegevens v die persoon anoniem maken indien alles afgehandeld is : persoonsgegevens moeten dan verwijderd worden
als die persoon na x jaar weer lid wordt, is het een nieuw lid

2/ iemand die door admin geblokkeerd wordt -> dit blijft een lid ; datum en reden van blokkeren zouden moeten genoteerd worden (enkel zichtbaar voor admin)
deze persoon mag niet reserveren en geen auto's zien, wel nog inloggen en afrekeningen bekijken

**Comment by genoot** [comment]
deze toevoeging is nuttg voor het opvolgen vd slordige betalers. 
als we hen nu blokkeren, weten we niet altijd waarom dit gebeurd is; 
en ze kunnen hun (volgende) afrekening niet meer bekijken.

**Comment by genoot** [comment]
wordt dringend voor opvolging wanbetalers

**Comment by driesdv** [comment]
geblokkeerd lid mag geen auto's zien noch reservaties maken
moet wel afrekening kunnen zien
