### ISSUE TITLE
invullen datum contract op infosessie

### ISSUE THREAD

**Issue by genoot** [degage/degapp#244]
Ook van kandidaten die op een infosessie al een contract tekenen, zou een contractdatum moeten ingevuld kunnen worden door een contractadmin. 
Het knopje voor het invullen vd contractdatum is nu niet zichtbaar bij het profiel van de gebruiker (wel het knopje voor het invullen van borg/lidgeld.

**Comment by genoot** [comment]
Een infosessiegever heeft nog geen rechten om profiel van lid op eigen infosessie te zien. Knopje voor contract is daardoor niet zichtbaar.
Kan dit ingesteld zonder infosessiegever ook profielbeheerder te maken voor alle leden ?

**Comment by driesdv** [comment]
Dat zou nu moeten lukken op de test server http://swiftbooks.corbit.be:9000/degapp


On 1 Mar 2017, at 13:02, genoot <notifications@github.com<mailto:notifications@github.com>> wrote:


Een infosessiegever heeft nog geen rechten om profiel van lid op eigen infosessie te zien. Knopje voor contract is daardoor niet zichtbaar.
Kan dit ingesteld zonder infosessiegever ook profielbeheerder te maken voor alle leden ?

**Comment by genoot** [comment]
dat lukt.
na het invullen van een contractdatum wordt de ledenlijst getoond.
beter is opnieuw de deelnemers aan de infosessie te tonen.

**Comment by driesdv** [comment]
Infosessies -> details -> klik op persoon -> contractdatum aanpassen
