### ISSUE TITLE
gegevens vorige/volgende ontlener verdwijnen

### ISSUE THREAD

**Issue by genoot** [degage/degapp#246]
gegevens vd vorige ontlener zijn niet meer te zien als de rit begonnen (voorbij) is,
noch door diegene wiens rit bezig is, als door diegene wiens rit net achter de rug is.

niet zeker of dat pas na de laatste update het geval is, het werd nu gesignaleerd.

**Comment by driesdv** [comment]
tijdspanne van 24 uur mag weg
