### ISSUE TITLE
Aandachtspunten afrekening : tankbeurten ontbreken

### ISSUE THREAD

**Issue by genoot** [degage/degapp#260]
Tankbeurten die nog niet gekeurd zijn, dienen ook bij de "aandachtspunten" te verschijnen.
Tabblad tankbeurten.

**Comment by genoot** [comment]
voorgaande is nog niet opgelost.

**Comment by driesdv** [comment]
Zijn dat niet degene die helemaal onderaan in de lijst van tankbeurten staan?

**Comment by driesdv** [comment]
sorteren per auto en extra kolom met soort probleem

**Comment by genoot** [comment]
en afgekeurde tankbeurten mogen niet meegerekend worden als mogelijke dubbels
