### ISSUE TITLE
extra velden autofiche

### ISSUE THREAD

**Issue by genoot** [degage/degapp#263]
Op de autofiche zijn extra velden nodig:

bij details (zichtbaar voor ontlener)
- ecoscore (getal)

bij geheime details (hernoemen naar technische details) (enkel zichtbaar voor eigenaar en admin)
- startdatum
- KW: getal

bij verzekeringsinfo
- startdatum polis: datum
- start BM: getal
- BA: ja/nee of vinkje
- Rechtsbijstand: ja/nee of vinkje
- Bestuurdersvezekering: ja/nee of vinkje
- Stoffelijke schade: ja/nee of vinkje
- huidige waarde BTWex: bedrag
- vrijstelling: (bedrag)
- Glasbreuk: ja/nee of vinkje
- Diefstal: ja/nee of vinkje

**Comment by genoot** [comment]
naast ecoscore dient ook 'euronorm' te komen, ook zichtbaar voor ontlener

**Comment by driesdv** [comment]
Wat wordt juist bedoeld met start datum? Is dat de start datum van de verzekering?

**Comment by genoot** [comment]
startdatum = vanaf wanneer de auto wordt gedeeld
stardatum polis = wanneer de verzekering start

beide data zijn door autobeheerder manueel in te vullen.
