### ISSUE TITLE
autokosten "in behandeling"

### ISSUE THREAD

**Issue by genoot** [degage/degapp#265]
Bij keuren van autokosten, is er regelmatig extra uitleg nodig (vraag voor correcte bewijsstuk, foutief bedrag vermeld,...). Wat nu via mail gebeurt, wordt beter via degapp afgehandeld.
Dat kan als car_admin commentaar kan schrijven bij een kost, en die kost de status "in behandeling" kan geven, voor de definitieve goedkeuring. De commentaren moeten zichtbaar zijn voor car_owner; het antwoord van car_owner ook zichtbaar voor de car_admin.

Kosten "in behandeling" mogen in de lijst in een apart tabblad komen.

**Comment by genoot** [comment]
eventueel het idee opnieuw oppikken om een bericht/vraag van het systeem te pushen naar het dashboard van de gebruiker . zie #115

**Comment by driesdv** [comment]
Bericht mag weg van dashboard als kost is goedgekeurd
