### ISSUE TITLE
infosessies meer dan volzet

### ISSUE THREAD

**Issue by genoot** [degage/degapp#273]
Mensen kunnen zich nog inschrijven als de infosessie volzet is.
Is nu het geval bij de infosessies met id 108 en 119.
Soms voegen wij achteraf nog mensen manueel toe aan een infosessie, ook al is het volzet. Dat blijft wel handig.
![volzet](https://cloud.githubusercontent.com/assets/9049321/22455998/1725c430-e790-11e6-9891-aeae27669d08.png)

**Comment by genoot** [comment]
zou er een datumprobleem zijn ?
het werkte in 2015 en 2016

**Comment by eisebaert** [comment]
Hoe werkte het vroeger? Versta ik het goed dat op .../degapp/infosession (waar de infosessies opgelijst zijn voor een gewone gebruiker) de "volzette" sessies niet getoond mogen worden? Of enkel de "inschrijven"-knop gedisabled?

**Comment by genoot** [comment]
Niet zeker hoe het voordien werkte. 
Nu worden volzette sessies getoond, maar inschrijven blijft mogelijk. 
Melding volzet verdwijnt zelfs als het aantal overschreden wordt.
Geen voorkeur of ze verdwijnen uit de lijst - of de knop inschrijven inactief staat.
Wel dient de sessie opnieuw te verschijnen als iemand zich uitschrijft en er een plaats over is.

buiten degapp worden de volzette sessies wel getoond. dat mag blijven.
http://www.degage.be/autodelen/infosessie/

**Comment by genoot** [comment]
Mogelijk is het een oude bug en wordt de info 'volzet' nu pas genegeerd ....
