### ISSUE TITLE
Debiteurenbeheer : afvinken betalingen obv coda

### ISSUE THREAD

**Issue by genoot** [degage/degapp#280]
- upload van een coda bestand (of xls, csv  beter ?)
-- Hoe start en stop bepalen ?
begin/einddatum?
Nr uittreksel ?
-- Dit zal meerdere keren per maand gebeuren
--Filenaam relevant ?
--Na inlezen bestand niet meer nodig
--Bank = Triodos

- ogm vergelijken met afrekeningen
-- indien bedrag en ogm gelijk dan mag het afgevinkt worden
we willen de  betalingsdatum weten 
-- de niet afgepunte bedragen moeten we daarna te zien krijgen om zelf af te vinken waar nodig (vb ogm klopt, correct bedrag niet betaald)

- steeds de mogelijkheid hebben om zelf af te vinken als betaald
--opmerkingenveld bij de persoon per afrekening
--voor afbetalingsplannen, blokkeren, …
--bedrag moeten we kunnen invullen vb als in meerdere keren betaald wordt
--indien al een bedrag is ingevuld mag er niets gebeuren
vb betaald in 2 keren met dezelfde ogm

- doorheen alle betaalde/onbetaalde / gedeeltelijke betaalde kunnen zoeken op volledig of deel van : 
bedrag, ogm, naam, voornaam, mededeling 

- mensen die geld terug krijgen worden nooit als onbetaald aanzien
het moet mogelijk zijn deze af te vinden als ‘terugbetaald’
terubetalingen, kunnen deze ook verwerkt worden als afgevinkt ???

- kunnen blokkeren omwille van wanbetaling of status 3de rappel
--na login krijgen deze mensen de melding dat ze moeten betalen maar ze kunnen er wel doorheen ? of niet doorheen ?
--het moet mogelijk zijn dit toch af te zetten vb als er een afbetalingsplan is of discussie over de factuur die niet binnen die tijd is opgelost.
--tekst : Beste, volgens onze info zijn er nog afrekeningen niet betaald. Maak dit snel in orde zoadat je opnieuw kan rijden met onze deelauto’s. Mocht je toch betaald hebben, geef ons zeker een seintje via admin@degage.be

- mail kunnen sturen naar wie nog niet betaalde  (aanvinken of bulk)
-- 1e en 2e herinnering versturen per kwartaal
-- daarna individueel per lijn die niet betaald is (link naar profiel op die lijn volstaat, is toch manuele opvolging

- op naam kunnen doorklikken op tel nr/email gegevens te zien

- bij lijst onbetaalde, allen tonen van oud naar nieuw

- lijst kunnen zien van bedrag per kwartaal, wat al betaald is en wat niet, plus datum van betaling, deadline betaling (om zo rapport van gemiddelde betalingstermijn te kunnen opmaken)

**Comment by driesdv** [comment]
To do:

default onbetaalde facturen  tonen en recente
uniciteit checken
bijhouden coda’s in tabel
eerst bedrag checken en dan pas rek nr
indien meerdere personen aan 1 rek nr , dan geen gebruiker kiezen
negatieve getallen ook verwerken
mensen excluden van rappels
