### ISSUE TITLE
export standplaatsen 

### ISSUE THREAD

**Issue by genoot** [degage/degapp#290]
json of kmz bestand om de standplaatsen van onze deelauto's (dagelijks) te exporteren.
- voor ons eigen kaartje met deelauto's
- voor derden die dit als layer op een kaart willen zetten.

**Comment by driesdv** [comment]
Which data should it contain exactly (name, gps coordinates, ... ?)

**Comment by genoot** [comment]
enkel actieve auto's selecteren
