### ISSUE TITLE
preview tankbewijs wordt niet altijd getoond

### ISSUE THREAD

**Issue by genoot** [degage/degapp#304]
de preview van een tankbewijs wordt soms niet getoond.
bvb http://www.degage.be/degapp/refuels/details?id=5414
rechtstreeks is het wel zichtbaar
http://www.degage.be/degapp/refuels/proof?id=5414
maar eigenaar kan hier niet rechtstreeks aan

**Comment by genoot** [comment]
ook als het wel getoond wordt op de preview, maar te klein en niet leesbaar is, moet er op de initiele link gekeken worden.

**Comment by degerrit** [comment]
Ander voorbeeld:
http://www.degage.be/degapp/refuels/details?id=6145
http://www.degage.be/degapp/refuels/proof?id=6145

Oorzaak (in dit geval iig) lijkt me te zijn dat in een img tag verwezen wordt naar iets dat een PDF is?
`<img src="/degapp/refuels/proof?id=6145" alt="" class="img-responsive">`
Denk niet dat veel browsers dat zo zullen renderen!
