### ISSUE TITLE
Gebruiker moet uitloggen om een statuswijziging te zien

### ISSUE THREAD

**Issue by Lootens** [degage/degapp#86]
bij een nieuwe eigenaar waar je de auto aan kan koppelen ziet de eigenaar pas de auto na logoff logon
kan dit via aan een refresh ?

**Comment by kcoolsae** [comment]
Wanneer de status van een gebruiker wijzigt, dan krijgt hij dit niet te zien zonder eerst uit te loggen.

De applicatie zou statuswijzigingen van een gebruiker moeten detecteren en sowieso opnieuw checken als de gebruiker te lang is uitgelogd. Het gemakkelijkste is wellicht om een 'vervaldatum' op de cookies te plakken.
