### ISSUE TITLE
profiel 100 %

### ISSUE THREAD

**Issue by Lootens** [degage/degapp#91]
mijn rijbewijs is nog niet opgeladen, nr en uitgifte datum is nog niet ingevuld
toch komt de melding dat profiel 100 % is

**Comment by kcoolsae** [comment]
Momenteel wordt het percentage bepaald aan de hand van de volgend items:

adressen (2x)
naam, voornaam, email, telefoonnummer 2x
identiteitskaartnummer

Wat zou er volgens u allemaal in rekening moeten gebracht worden?

Let op: 'profiel' is niet hetzelfde als 'wat is er nodig om lid te worden', maar misschien zou het dat moeten zijn. En in dat geval zou ik het percentage misschien niet meer tonen bij mensen die al lid zijn.

**Comment by genoot** [comment]
voor 100% zijn ook nodig 

rijksregisternummer
ID bestand
rijbewijs nr
rijbewijs bestand
profielfoto

verschillen met eisen om lid te worden:
extra nodig : infoessie, waarborg en contract

Profiel dient door iedereen aangevuld, ook door bestaande leden.
Percentage of andere aanmoediging is daarvoor handig.

**Comment by genoot** [comment]
met alles ingevuld geraak ik tot 90%
worden contract en infosessie worden meegerekend ?

**Comment by genoot** [comment]
de profielfoto wordt nog niet meegeteld om tot 100% te komen.
dat zou ik wel doen.
een profiel met de standaard afbeelding is toch maar niets.

**Comment by genoot** [comment]
we moedigen leden om hun profiel tot 100% in te vullen maar dat levert te weinig op.
vaak ontbreken nog adres, id of rijbewijs of telnr bij oude leden.
is het doenbaar reservaties pas toe te laten als het profiel 100% is aangevuld ?
en hen bij het inloggen meteen te laten starten op de onvolledige profielpagina ?
