### ISSUE TITLE
Geprivilegieerden kunnen enkel worden aangeduid door admin

### ISSUE THREAD

**Issue by kcoolsae** [degage/degapp#96]
De huidige userinterface is nog een beetje laks op dit domein.

**Comment by genoot** [comment]
dat was de bedoeling.
een eigenaar mag niet telkens de VIP kunnen wijzigen.
admin wel, als de eigenaar dit vraagt
een beheerder van de auto's zou dit ook mogen

**Comment by genoot** [comment]
nu kan ik als eigenaar wel meerdere VIPS toevoegen aan mijn auto.
heb er nu 3 VIP gemaakt van klorofil maar die personen zien dat nu niet.
als eigenaar zie ik wel hun namen bij details vd auto.
of ze nu VIP zijn is niet duidelijk.

**Comment by genoot** [comment]
deze interface is ook voor admin weg
